#!/bin/bash -ex
# inspired from https://gist.github.com/2913223


##########################################
# Only needed if starting from fresh $HOME
##########################################
if [[ ! -e $HOME/.homesick ]]; then
  # Prerequisites to run this script:
  # SSH key that Github understands so we can checkout our dotfiles repo
  
  sudo dnf install git curl
  # Install Homeshick
  git clone git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
  printf '\nsource $HOME/.homesick/repos/homeshick/homeshick.sh\n' >> $HOME/.bashrc
  source $HOME/.bashrc
  
  homeshick clone git@github.com:binarybana/dotfiles.git
  # Answer n when it asks to symlink
  
  mv $HOME/.ssh $HOME/ssh
  homeshick symlink dotfiles
  cp -a ssh/* $HOME/.homesick/repos/dotfiles/home/.ssh
  rm -rf $HOME/ssh
  
  # Get a local copy of GSP/ and Dropbox/ if available
  # Install btsync
  
  #echo "openout_any = a" >> /usr/share/texlive/texmf-dist/web2c/texmf.cnf
fi
##########################################
# endif
##########################################

sudo dnf install $(cat $HOME/.homesick/repos/dotfiles/pkg-list.yum)

chsh --shell /bin/zsh

su -c 'yum localinstall -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm'

su -c 'yum localinstall --nogpgcheck -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'

# In fedora install Infinilaty text rendering patches:
su -c 'yum localinstall -y http://www.infinality.net/fedora/linux/infinality-repo-1.0-1.noarch.rpm'
sudo dnf install -y freetype-infinality fontconfig-infinality gstreamer-plugins-bad-nonfree
