#!/bin/bash -ex
# inspired from https://gist.github.com/2913223

# On a brand new system, the first step is to update and then
# acquire git and curl
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install git curl dselect

curl -s https://raw.github.com/andsens/homeshick/master/install.sh | bash

## Now you'll need to put your ssh private key on github so that we can...
$HOME/.homeshick clone git@github.com:binarybana/dotfiles.git

mv $HOME/.ssh $HOME/ssh
$HOME/.homeshick symlink dotfiles
cp -a ssh/* $HOME/.homesick/repos/dotfiles/home/.ssh
rm -rf $HOME/.ssh

# It appears there may be a bug in dpkg and there is a workaround that we're using here:
# http://rayslinux.blogspot.com/2012/10/ubuntu-1210-dpkg-warning-package-not-in.html
sudo dselect update
sudo dpkg --set-selections <$HOME/.homesick/repos/dotfiles/pkg-list 
sudo apt-get -u dselect-upgrade

chsh --shell /bin/zsh

echo "Now I need to get the rest of the files from:"
echo "bin .s3ql .unison .ssh GSP Dropbox"

# S3QL
sudo mkdir /mnt/gs
sudo chown bana /mnt/gs
sudo chgrp bana /mnt/gs
# cp ~/.s3ql/authinfo2 from somewhere
# cp ~/.unison/gsp.prf from somewhere
# try to cp ~/bin/unison from somewhere

#mount.s3ql gs://jknight-s3-test /mnt/gs

# get as much of GSP locally as you can (avoid pulling the whole data set)
# then:

#rsync -avP --delete --size-only /mnt/gs ~/GSP/

#unison -fastercheckUNSAFE /mnt/gs/ ~/GSP/
#unison gsp

#umount.s3ql /mnt/gs
#sync
